# Generated by Django 3.0.8 on 2020-07-18 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='city_id',
            new_name='city',
        ),
    ]
