# Generated by Django 3.0.8 on 2020-07-18 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200718_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='city',
            new_name='city_id',
        ),
    ]
