# Generated by Django 3.0.8 on 2020-07-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20200718_0736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'ordering': ['city_id', 'date']},
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='city_id',
            new_name='city',
        ),
    ]
